Importando bibliotecas

In [81]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Carregando os dados originais

In [82]:
df = pd.read_csv('data/game_info_original.csv')

### Definições das colunas:
- `id`: An unique ID identifying this Game in RAWG Database
- `slug`: An unique slug identifying this Game in RAWG Database
- `name`: Name of the game
- `metacritic`: Rating of the game on [Metacritic](https://www.metacritic.com/game)
- `released`: The date the game was released
- `tba`: To be announced state
- `updated`: The date the game was last updated
- `website`: Game Website
- `rating`: Rating rated by RAWG user
- `rating_top`: Maximum rating
- `playtime`: Hours needed to complete the game
- `achievements_count`: Number of achievements in game
- `ratings_count`: Number of RAWG users who rated the game
- `suggestions_count`: Number of RAWG users who suggested the game
- `game_series_count`: Number of games in the series
- `reviews_count`: Number of RAWG users who reviewed the game
- `platforms`: Platforms game was released on. **Separated** by `||`
- `developers`: Game developers. **Separated** by `||`
- `genres`: Game genres. **Separated** by `||`
- `publishers`: Game publishers. **Separated** by `||`
- `esrb_rating`: ESRB ratings
- `added_status_yet`: Number of RAWG users had the game as "Not played"
- `added_status_owned`: Number of RAWG users had the game as "Owned"
- `added_status_beaten`: Number of RAWG users had the game as "Completed"
- `added_status_toplay`: Number of RAWG users had the game as "To play"
- `added_status_dropped`: Number of RAWG users had the game as "Played but not beaten"
- `added_status_playing`: Number of RAWG users had the game as "Playing"

In [83]:
df.head()

,id,slug,name,metacritic,released,tba,updated,website,rating,rating_top,...,developers,genres,publishers,esrb_rating,added_status_yet,added_status_owned,added_status_beaten,added_status_toplay,added_status_dropped,added_status_playing
0,1,dgeneration-hd,D/Generation HD,NaN,2015-10-23,False,2019-09-17T11:58:57,http://dgeneration.net,0.0,0,...,West Coast Software,Adventure||Puzzle,West Coast Software,Everyone 10+,4,88,2,2,0,0
1,10,g-prime,G Prime Into The Rain,NaN,2016-01-06,False,2019-11-06T23:04:19,NaN,0.0,0,...,Soma Games,Simulation||Indie,Immanitas Entertainment||Code-Monkeys,Everyone,2,42,2,0,0,0
2,100,land-sliders,Land Sliders,NaN,2015-09-24,False,2019-10-22T13:56:16,http://prettygreat.com,0.0,0,...,Prettygreat Pty,Adventure||Arcade,Prettygreat Pty,Everyone 10+,0,2,2,0,1,0
3,1000,pixel-gear,Pixel Gear,NaN,2016-10-20,False,2019-08-28T22:16:02,https://www.facebook.com/Geronimo-Interactive-...,0.0,0,...,Oasis Games||Geronimo Interactive,Action||Indie,Geronimo Interactive,Teen,0,1,0,0,0,0
4,10000,gods-and-idols,Gods and Idols,NaN,2016-12-12,False,2019-09-17T13:37:13,http://www.godsandidols.com/,0.0,1,...,Viking Tao,RPG||Strategy||Massively Multiplayer,Viking Tao,NaN,2,79,0,0,0,0

***
# Tratando os dados

## Removendo linhas

É do nosso interesse remover jogos que ainda não foram lançados, jogos que não possuem plataforma de lançamento ou que não possuem gênero. Também queremos remover jogos que não possuem nem nota do público, nem nota do Metacritic.

In [84]:
df = df[df["tba"] == False]
df = df[df["platforms"].notna()]
df = df[df["genres"].notna()]
df = df[(df["reviews_count"] > 0) | (df["metacritic"].notna())]
df

,id,slug,name,metacritic,released,tba,updated,website,rating,rating_top,...,developers,genres,publishers,esrb_rating,added_status_yet,added_status_owned,added_status_beaten,added_status_toplay,added_status_dropped,added_status_playing
0,1,dgeneration-hd,D/Generation HD,NaN,2015-10-23,False,2019-09-17T11:58:57,http://dgeneration.net,0.00,0,...,West Coast Software,Adventure||Puzzle,West Coast Software,Everyone 10+,4,88,2,2,0,0
1,10,g-prime,G Prime Into The Rain,NaN,2016-01-06,False,2019-11-06T23:04:19,NaN,0.00,0,...,Soma Games,Simulation||Indie,Immanitas Entertainment||Code-Monkeys,Everyone,2,42,2,0,0,0
2,100,land-sliders,Land Sliders,NaN,2015-09-24,False,2019-10-22T13:56:16,http://prettygreat.com,0.00,0,...,Prettygreat Pty,Adventure||Arcade,Prettygreat Pty,Everyone 10+,0,2,2,0,1,0
4,10000,gods-and-idols,Gods and Idols,NaN,2016-12-12,False,2019-09-17T13:37:13,http://www.godsandidols.com/,0.00,1,...,Viking Tao,RPG||Strategy||Massively Multiplayer,Viking Tao,NaN,2,79,0,0,0,0
13,10001,serious-sam-fusion-2017-beta,Serious Sam Fusion 2017 (beta),NaN,2017-03-20,False,2020-03-08T19:03:42,http://www.croteam.com,3.07,4,...,Croteam,Action||Indie,Devolver Digital||Croteam,NaN,200,3292,41,11,79,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474376,9996,sailaway-the-sailing-simulator,Sailaway - The Sailing Simulator,NaN,2017-04-25,False,2019-08-28T22:14:40,http://www.sailawaysimulator.com/,0.00,0,...,Orbcreation,Simulation||Indie,The Irregular,NaN,1,9,0,1,1,0
474387,9997,arma-3,Arma 3,74.0,2013-09-12,False,2020-03-17T20:07:08,http://www.arma3.com,3.84,4,...,Bohemia Interactive,Action||Shooter||Strategy||Simulation,Bohemia Interactive,NaN,38,1357,54,20,127,32
474398,9998,nation-red,Nation Red,NaN,2009-08-02,False,2019-09-17T05:23:55,http://www.nation-red.com,2.54,3,...,DiezelPower,Action||Indie,DiezelPower,NaN,16,447,10,0,25,3
474404,99986,echoes-of-a-forgotten-realm-prototype,Echoes of a Forgotten Realm (Prototype),NaN,2017-03-20,False,2019-01-09T12:41:06,NaN,0.00,0,...,CaptainSteamFox,Platformer,NaN,NaN,0,0,0,0,0,0
474407,9999,pixel-privateers,Pixel Privateers,NaN,2017-02-21,False,2019-08-28T22:14:40,http://pixelprivateers.com,0.00,3,...,Quadro Delta,Action||Adventure||RPG||Simulation||Indie,Re-Logic,NaN,1,36,0,1,1,0

## Removendo colunas
 
Aqui, começamos removendo algumas colunas que não usaremos em nenhum momento, para deixar o DataFrame mais leve. Algumas colunas serão mantidas para a análise exploratória, mas serão removidas futuramente.

In [85]:
df0 = df.drop(columns=["id", 
                      "name", 
                      "slug", 
                      "tba", 
                      "updated", 
                      "website", 
                      "rating_top", 
                      "ratings_count", 
                      "suggestions_count", 
                      "reviews_count", 
                      "developers", 
                      "publishers",
                      "added_status_yet",
                      "added_status_owned",
                      "added_status_toplay",
                      "added_status_playing"])
df0.columns

Index(['metacritic', 'released', 'rating', 'playtime', 'achievements_count',
       'game_series_count', 'platforms', 'genres', 'esrb_rating',
       'added_status_beaten', 'added_status_dropped'],
      dtype='object')

## Tratando Plataformas
Tratando a coluna plataformas, queremos resumir as plataformas menos importantes, e transformá-la em várias colunas booleanas de classes não excludentes.

In [86]:
df0["platforms"] = df0["platforms"].apply(lambda x: x.split("||") if type(x) == str else x)

df0["platforms"] = df0["platforms"].apply(lambda x: ["PlayStation" if ("PlayStation" in i) or (i in ["PSP", "PS Vita"]) else i for i in x])
df0["platforms"] = df0["platforms"].apply(lambda x: ["Xbox" if "Xbox" in i else i for i in x])
df0["platforms"] = df0["platforms"].apply(lambda x: ["PC" if i in ["macOS", "PC", "Linux", "Apple II"] else i for i in x])
df0["platforms"] = df0["platforms"].apply(lambda x: ["Nintendo" if ("Nintendo" in i) or (i in ["Wii", "Wii U", "Game Boy", "Game Boy Color", "Game Boy Advance", "GameCube", "NES", "SNES"]) else i for i in x])
df0["platforms"] = df0["platforms"].apply(lambda x: ["Mobile" if i in ["Android", "iOS"] else i for i in x])

# If not any of the above, replace with "Other"
df0["platforms"] = df0["platforms"].apply(lambda x: ["Other" if i not in ["PlayStation", "Xbox", "PC", "Nintendo", "Mobile"] else i for i in x])

# Remove duplicates
df0["platforms"] = df0["platforms"].apply(lambda x: list(set(x)))

# We can see how many games are available on each platform
df0["platforms"].explode().value_counts()

platforms
PC             25715
PlayStation     7795
Mobile          5789
Nintendo        5557
Xbox            4774
Other           2034
Name: count, dtype: int64

Expande as classes de plataforma de forma que cada classe tenha sua própria coluna com valor binário.

In [87]:
platforms_dummies = pd.get_dummies(df0["platforms"].explode(), "platform")
platforms_classes = platforms_dummies.groupby(platforms_dummies.index).sum()
platforms_classes

,platform_Mobile,platform_Nintendo,platform_Other,platform_PC,platform_PlayStation,platform_Xbox
0,0,1,0,1,1,1
1,0,0,0,1,0,1
2,1,0,0,0,0,0
4,0,0,0,1,0,0
13,0,0,0,1,0,0
...,...,...,...,...,...,...
474376,0,0,0,1,0,0
474387,0,0,0,1,0,0
474398,0,0,0,1,0,0
474404,1,0,0,1,0,0
474407,0,0,0,1,0,0

Por fim, agrega as classes na tabela original, e remove a antiga coluna.

In [88]:
df1 = df0.drop(columns=["platforms"]).join(platforms_classes)
df1.head()

,metacritic,released,rating,playtime,achievements_count,game_series_count,genres,esrb_rating,added_status_beaten,added_status_dropped,platform_Mobile,platform_Nintendo,platform_Other,platform_PC,platform_PlayStation,platform_Xbox
0,NaN,2015-10-23,0.00,1,80,0,Adventure||Puzzle,Everyone 10+,2,0,0,1,0,1,1,1
1,NaN,2016-01-06,0.00,0,26,0,Simulation||Indie,Everyone,2,0,0,0,0,1,0,1
2,NaN,2015-09-24,0.00,0,0,0,Adventure||Arcade,Everyone 10+,2,1,1,0,0,0,0,0
4,NaN,2016-12-12,0.00,1,0,0,RPG||Strategy||Massively Multiplayer,NaN,0,0,0,0,0,1,0,0
13,NaN,2017-03-20,3.07,1,76,19,Action||Indie,NaN,41,79,0,0,0,1,0,0

## Tratando Gêneros
Faremos etapas parecidas para criar novas colunas de classes de gênero.

In [89]:
df1["genres"] = df1["genres"].apply(lambda x: x.split("||"))

# Remove duplicates
df1["genres"] = df1["genres"].apply(lambda x: list(set(x)))

In [90]:
genre_dummies = pd.get_dummies(df1["genres"].explode(), "genre")
genre_classes = genre_dummies.groupby(genre_dummies.index).sum()
for col in genre_classes.columns:
    genre_classes.rename(columns={col: col.replace(" ", "_")}, inplace=True)
genre_classes

,genre_Action,genre_Adventure,genre_Arcade,genre_Board_Games,genre_Card,genre_Casual,genre_Educational,genre_Family,genre_Fighting,genre_Indie,genre_Massively_Multiplayer,genre_Platformer,genre_Puzzle,genre_RPG,genre_Racing,genre_Shooter,genre_Simulation,genre_Sports,genre_Strategy
0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
2,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1
13,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474376,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
474387,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1
474398,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
474404,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
474407,1,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0

In [91]:
df2 = df1.drop(columns=["genres"]).join(genre_classes)
df2.head()

,metacritic,released,rating,playtime,achievements_count,game_series_count,esrb_rating,added_status_beaten,added_status_dropped,platform_Mobile,...,genre_Indie,genre_Massively_Multiplayer,genre_Platformer,genre_Puzzle,genre_RPG,genre_Racing,genre_Shooter,genre_Simulation,genre_Sports,genre_Strategy
0,NaN,2015-10-23,0.00,1,80,0,Everyone 10+,2,0,0,...,0,0,0,1,0,0,0,0,0,0
1,NaN,2016-01-06,0.00,0,26,0,Everyone,2,0,0,...,1,0,0,0,0,0,0,1,0,0
2,NaN,2015-09-24,0.00,0,0,0,Everyone 10+,2,1,1,...,0,0,0,0,0,0,0,0,0,0
4,NaN,2016-12-12,0.00,1,0,0,NaN,0,0,0,...,0,1,0,0,1,0,0,0,0,1
13,NaN,2017-03-20,3.07,1,76,19,NaN,41,79,0,...,1,0,0,0,0,0,0,0,0,0

## Criando coluna de 'drop'

Aqui, usaremos as informações de status para saber, de todos os usuários que em algum momento começaram e pararam de jogar, quantos deles terminaram o jogo e quantos pararam na metade. Para que a análise não seja afetada pela quantia absoluta de jogadores, utilizaremos de porcentagem ao invés de números brutos.

In [94]:
df3 = df2
df3["users_drop_percent"] = df3["added_status_dropped"] / (df3["added_status_dropped"] + df3["added_status_beaten"])
df3 = df3.drop(columns=["added_status_dropped", "added_status_beaten"])
df3

,metacritic,released,rating,playtime,achievements_count,game_series_count,esrb_rating,platform_Mobile,platform_Nintendo,platform_Other,...,genre_Massively_Multiplayer,genre_Platformer,genre_Puzzle,genre_RPG,genre_Racing,genre_Shooter,genre_Simulation,genre_Sports,genre_Strategy,users_drop_percent
0,NaN,2015-10-23,0.00,1,80,0,Everyone 10+,0,1,0,...,0,0,1,0,0,0,0,0,0,0.000000
1,NaN,2016-01-06,0.00,0,26,0,Everyone,0,0,0,...,0,0,0,0,0,0,1,0,0,0.000000
2,NaN,2015-09-24,0.00,0,0,0,Everyone 10+,1,0,0,...,0,0,0,0,0,0,0,0,0,0.333333
4,NaN,2016-12-12,0.00,1,0,0,NaN,0,0,0,...,1,0,0,1,0,0,0,0,1,NaN
13,NaN,2017-03-20,3.07,1,76,19,NaN,0,0,0,...,0,0,0,0,0,0,0,0,0,0.658333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474376,NaN,2017-04-25,0.00,3,18,0,NaN,0,0,0,...,0,0,0,0,0,0,1,0,0,1.000000
474387,74.0,2013-09-12,3.84,19,98,0,NaN,0,0,0,...,0,0,0,0,0,1,1,0,1,0.701657
474398,NaN,2009-08-02,2.54,4,145,0,NaN,0,0,0,...,0,0,0,0,0,0,0,0,0,0.714286
474404,NaN,2017-03-20,0.00,0,0,0,NaN,1,0,0,...,0,1,0,0,0,0,0,0,0,NaN
474407,NaN,2017-02-21,0.00,6,0,0,NaN,0,0,0,...,0,0,0,1,0,0,1,0,0,1.000000

In [96]:
df3.columns

Index(['metacritic', 'released', 'rating', 'playtime', 'achievements_count',
       'game_series_count', 'esrb_rating', 'platform_Mobile',
       'platform_Nintendo', 'platform_Other', 'platform_PC',
       'platform_PlayStation', 'platform_Xbox', 'genre_Action',
       'genre_Adventure', 'genre_Arcade', 'genre_Board_Games', 'genre_Card',
       'genre_Casual', 'genre_Educational', 'genre_Family', 'genre_Fighting',
       'genre_Indie', 'genre_Massively_Multiplayer', 'genre_Platformer',
       'genre_Puzzle', 'genre_RPG', 'genre_Racing', 'genre_Shooter',
       'genre_Simulation', 'genre_Sports', 'genre_Strategy',
       'users_drop_percent'],
      dtype='object')

Isso conclui o tratamento de dados planejado para este projeto. Para mais insights acerca do dataset resultante deste processo, acesse o arquivo de análise exploratória!

In [97]:
df3.to_csv("data/game_info_treated.csv", index=False)